### ISSUE TITLE
Add instructions in Readme about installation

### ISSUE THREAD

**Issue by koustuvsinha** [NilanjanDaw/RemoteComputer-Server#1]
Add proper instructions in Readme for a new user to install & run the server the side code in their own machine.

**Comment by koustuvsinha** [comment]
The commit does not address this specific issue. Its about modifying the readme for installation notes. I think you have confused it with the same issue of the android client

**Comment by NilanjanDaw** [comment]
I have done the modifications. Things should be fine now. Thanks! @koustuvsinha
